name: provider
description: A wrapper around InheritedWidget to make them easier to use and more reusable.
version: 5.0.0-nullsafety.2
homepage: https://github.com/rrousselGit/provider

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">= 1.16.0"

dependencies:
  collection: ^1.15.0-nullsafety.5
  flutter:
    sdk: flutter
  nested: ^0.0.5-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
  test: ^1.15.5
